# Generated by Django 3.2.9 on 2022-03-23 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='content_details')),
                ('description_detail', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('votes', models.IntegerField(default=0)),
                ('cont', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.content')),
            ],
        ),
    ]
