# Generated by Django 3.2.9 on 2022-03-27 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdetails',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.channel'),
        ),
        migrations.AlterField(
            model_name='content',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.channel'),
        ),
        migrations.AlterField(
            model_name='contentdetails',
            name='cont',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.content'),
        ),
    ]
