# Generated by Django 3.2.9 on 2022-03-27 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220327_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdetails',
            name='file',
            field=models.FileField(default=0, upload_to='content_details'),
        ),
        migrations.AlterField(
            model_name='contentdetails',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.channel'),
        ),
    ]
