# Generated by Django 3.2.9 on 2022-03-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220327_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentdetails',
            name='file',
            field=models.FileField(upload_to='content_details'),
        ),
        migrations.AlterField(
            model_name='contentdetails',
            name='votes',
            field=models.IntegerField(),
        ),
    ]
